apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ubuntu
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ubuntu
    spec:
      runtimeClassName: gvisor
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["/bin/sleep"]
        args: ["infinity"]
        tty: true
        stdin: true
        securityContext:
          privileged: true
